import type { Metadata } from "next";
// 1. Impor font yang diinginkan dari next/font/google
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
 import Providers from "@/app/components/Providers";
import Navbar from "@/app/components/NavBar";

// 2. Konfigurasi font
const inter = Inter({
    subsets: ["latin"],
    variable: '--font-inter', // Buat CSS variable untuk font ini
    display: 'swap',
});

const poppins = Poppins({
    subsets: ["latin"],
    weight: ['400', '700'], // Tentukan ketebalan yang akan digunakan
    variable: '--font-poppins', // Buat CSS variable
    display: 'swap',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${inter.variable} ${poppins.variable}`}>
        <body className={inter.className}>
        {/* Bungkus children di dalam body, bukan seluruh html */}
        <Providers>
            <Navbar />
            <main>{children}</main>
        </Providers>
        </body>
        </html>
    );
}